name: Pull Request Labeler

on:
  pull_request:
    types:
      - closed
jobs:
  if_merged:
    if: ${{ github.event.pull_request.base.ref != 'main' && github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    steps:
    - name: Label Pull Request
      uses: ffittschen/pr-branch-labeler@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
