# This workflow is used to test updating of jira tickets
name: Test-Update-Jira-Tickets

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      newReleaseNumber:
        description: 'Release number'
        required: true
        default: '1.8.1'  
      isHotfix:
        description: 'Is hotfix'
        required: true
        default: 'true'  
  

#============================================================================
####################### Update Jira Tickets  #######################
#============================================================================
jobs:
  # Update Jira Tickets
  update_jira_tickets:    
    name: Update Jira Tickets
    runs-on: ubuntu-latest
    env:                 
      branch: ${{ github.ref }}
      changelogConfig: ".github/changelog-config.json"
      changelogConfigHotfix: ".github/changelog-config-hotfix.json"
      isHotfix: ${{ github.event.inputs.isHotfix }}

    steps: 
    
      - name: Override changelogConfig if hotfix
        if: ${{ env.isHotfix == 'true' }}
        run: |
          echo "changelogConfig=${{ env.changelogConfigHotfix }}" >> $GITHUB_ENV
          
      - name: Step1 - Checkout branch from Github
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
        
      - name: Build Changelog
        id: buildChangelogApp
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ${{ env.changelogConfig }}
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: "v${{ github.event.inputs.newReleaseNumber }}" 
          
      - name: Output changelog
        run: |
          cat << "EOF"
          ${{ steps.buildChangelogApp.outputs.changelog }}
          EOF
   
      - name: Update tickets using powershell script
        id: UpdateJiraTickets
        env:                 
          jiraUrl: ${{ secrets.JIRA_URL }}
          jiraUser: ${{ secrets.JIRA_USER }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          runNumber: ${{ github.run_number }}
        shell: pwsh
        run: |
          Write-Output "Input value for Is Hotfix ${{ env.isHotfix }}"
          Write-Output "Input value for Run Number ${{ env.runNumber }}"

          ./update-jira-tickets.ps1 -isHotfix "${{ env.isHotfix }}" -runNumber "${{ env.runNumber }}" -appTickets "${{ steps.buildChangelogApp.outputs.changelog }}" -dbTickets "JEM-8888" -wsTickets "JEM-2222JEM-2333" 
          
