# This workflow is used to test release notes action
name: Test-Release-Notes

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      newReleaseNumber:
        description: 'Release number'
        required: true
      isHotfix:
        description: 'Is hotfix'
        required: true
        default: false
  

#============================================================================
####################### Build release    #######################
#============================================================================
jobs:
  # Build release notes
  build_release_notes:    
    name: Build release notes
    runs-on: ubuntu-latest
    env:                 
      branch: ${{ github.ref }}
      changelogConfig: ".github/changelog-config.json"
      changelogConfigHotfix: ".github/changelog-config-hotfix.json"

    steps: 
    
      - name: Override changelogConfig if hotfix
        if: ${{ github.event.inputs.isHotfix == "true" }}
        run: |
          echo "changelogConfig=${{ env.changelogConfigHotfix }}" >> $GITHUB_ENV
          
      - name: Step1 - Checkout branch from Github
        uses: actions/checkout@v3
        with:
          ref: ${{ env.branch }}
        
      - name: Build Changelog
        id: buildChangelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: ${{ env.changelogConfig }}
          token: ${{ secrets.GITHUB_TOKEN }}
          toTag: "v${{ github.event.inputs.newReleaseNumber }}" 
          
      - name: Output changelog
        run: |
          cat << "EOF"
          ${{ steps.buildChangelog.outputs.changelog }}
          EOF
   
